#
# File: services.yml
# Description: Restart vagrant services
#
---

- hosts: "*"
  no_log: True

  #
  # Variables
  #
  vars:
    - services:
        - 'mysql'
        - 'nginx'
        - 'solr'
        - 'unoconvd'

  #
  # Tasks
  #
  tasks:
    - name: "SOLR | Restart services."
      shell: "service {{ item }} restart"
      with_items: "{{ services }}"
      become: yes