#
# File: ssh.yml
# Description: Generate RSA keys.
#
---

- hosts: "*"

  #
  # Variables
  #
  vars:
    - ssh_users:
        - 'vagrant'
        - 'root'

  #
  # Tasks
  #
  tasks:
    - name: 'USER | Generating RSA key for users'
      user: name={{ item }} generate_ssh_key=yes
      become: yes
      with_items: "{{ ssh_users }}"
