#
# file: sysctl/tasks/ipv4.yml
# Manage network settings
#
---

- name: Disable config ipv6 (all)
  sysctl: name="net.ipv6.conf.all.disable_ipv6"
          value=1
          sysctl_set=yes
          state=present
  become: yes

- name: Disable config ipv6 (default)
  sysctl: name="net.ipv6.conf.default.disable_ipv6 "
          value=1
          sysctl_set=yes
          state=present
  become: yes

- name: Disable config ipv6 (lo)
  sysctl: name="net.ipv6.conf.lo.disable_ipv6 "
          value=1
          sysctl_set=yes
          state=present
  become: yes
